{
 "title": "Health",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "血氧饱和度",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS SPO,\n  (timestamp - interval '8 hours') AS time\nFROM\n  metrics\nWHERE\n  name = 'blood_oxygen_saturation'\n  AND \"timestamp\" > ($__timeFrom()::timestamp + interval '8 hours')\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')"
    }
   ]
  },
  {
   "title": "心率变异性",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS HRV,\n  (timestamp - interval '8 hours') AS time\nFROM\n  metrics\nWHERE\n  name = 'heart_rate_variability'\n  AND \"timestamp\" > ($__timeFrom()::timestamp + interval '8 hours')\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')"
    }
   ]
  },
  {
   "title": "睡眠分析",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOALESCE(SUM((data ->> 'deep')::float), 0) AS deep,\n\tCOALESCE(SUM((data ->> 'core')::float), 0) AS core,\n\tCOALESCE(SUM((data ->> 'awake')::float), 0) AS awake,\n\tCOALESCE(SUM((data ->> 'rem')::float), 0) AS rem,\n\tgenerate_series(date_trunc('day', min(timestamp)), date_trunc('day', max(timestamp)), '1 day'::interval) AS time\nFROM\n\tmetrics\nWHERE\n\tname = 'sleep_analysis'\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')\n  AND \"timestamp\" > \n    CASE \n      WHEN $__timeTo()::timestamp - $__timeFrom()::timestamp >= interval '24 hours' \n      THEN date_trunc('day', $__timeFrom()::timestamp + interval '8 hours')\n      ELSE $__timeFrom()::timestamp + interval '8 hours'\n    END\nGROUP BY\n\tdate_trunc('day', timestamp)\nORDER BY\n\ttime;"
    }
   ]
  },
  {
   "title": "基础能量消耗",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS value,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'basal_energy_burned'\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')\n  AND \"timestamp\" > \n    CASE \n      WHEN $__timeTo()::timestamp - $__timeFrom()::timestamp >= interval '24 hours' \n      THEN date_trunc('day', $__timeFrom()::timestamp + interval '8 hours' + interval '1 day')\n      ELSE $__timeFrom()::timestamp + interval '8 hours'\n    END\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "活动能量",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS calorie,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'active_energy'\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')\n  AND \"timestamp\" > \n    CASE \n      WHEN $__timeTo()::timestamp - $__timeFrom()::timestamp >= interval '24 hours' \n      THEN date_trunc('day', $__timeFrom()::timestamp + interval '8 hours' + interval '1 day')\n      ELSE $__timeFrom()::timestamp + interval '8 hours'\n    END\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "步数",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS step,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'step_count'\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')\n  AND \"timestamp\" > \n    CASE \n      WHEN $__timeTo()::timestamp - $__timeFrom()::timestamp >= interval '24 hours' \n      THEN date_trunc('day', $__timeFrom()::timestamp + interval '8 hours' + interval '1 day')\n      ELSE $__timeFrom()::timestamp + interval '8 hours'\n    END\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "体重",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS kg,\n  (timestamp - interval '8 hours') AS time\nFROM\n  metrics\nWHERE\n  name = 'weight_body_mass'\n  AND \"timestamp\" > ($__timeFrom()::timestamp + interval '8 hours')\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')"
    }
   ]
  },
  {
   "title": "体脂率",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n\t(data ->> 'qty')::float AS body_fat_percentage,\n  (timestamp - interval '8 hours') AS time\nFROM\n\tmetrics\nWHERE\n\tname = 'body_fat_percentage';"
    }
   ]
  },
  {
   "title": "BMI",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n\t(data ->> 'qty')::float AS BMI,\n  (timestamp - interval '8 hours') AS time\nFROM\n\tmetrics\nWHERE\n\tname = 'body_mass_index';"
    }
   ]
  },
  {
   "title": "静息心率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS QPM,\n  (timestamp - interval '8 hours') AS time\nFROM\n  metrics\nWHERE\n  name = 'resting_heart_rate'\n  AND \"timestamp\" > ($__timeFrom()::timestamp + interval '8 hours')\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')"
    }
   ]
  }
 ]
}