{
 "title": "Declan-Health",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "体重/身体质量",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS kg,\n  timestamp AS time\nFROM\n  metrics\nWHERE\n  name = 'weight_body_mass'\n  AND \"timestamp\" >= $__timeFrom()\n  AND \"timestamp\" <= $__timeTo();"
    }
   ]
  },
  {
   "title": "步行/跑步距离",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS km,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'walking_running_distance'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "步数",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS step,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'step_count'\n  AND \"timestamp\" < ($__timeTo()::timestamp + interval '8 hours')\n  AND \"timestamp\" > \n    CASE \n      WHEN $__timeTo()::timestamp - $__timeFrom()::timestamp >= interval '24 hours' \n      THEN date_trunc('day', $__timeFrom()::timestamp + interval '8 hours' + interval '1 day')\n      ELSE $__timeFrom()::timestamp + interval '8 hours'\n    END\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "攀登楼层数",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS floor,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'flights_climbed'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "消耗能量",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS calorie,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'active_energy'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "基础能量消耗",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS value,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'basal_energy_burned'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "睡眠分析",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOALESCE(SUM((data ->> 'deep')::float), 0) AS deep,\n\tCOALESCE(SUM((data ->> 'core')::float), 0) AS core,\n\tCOALESCE(SUM((data ->> 'awake')::float), 0) AS awake,\n\tCOALESCE(SUM((data ->> 'rem')::float), 0) AS rem,\n\tgenerate_series(date_trunc('day', min(timestamp)), date_trunc('day', max(timestamp)), '1 day'::interval) AS time\nFROM\n\tmetrics\nWHERE\n\tname = 'sleep_analysis'\n\tAND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n\tdate_trunc('day', timestamp)\nORDER BY\n\ttime;"
    }
   ]
  },
  {
   "title": "去脂体重",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(AVG((data ->> 'qty') :: float), 0) AS kg,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'lean_body_mass'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "锻炼时间",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 14, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS minute,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'apple_exercise_time'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "体脂百分比",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n\t(data ->> 'qty')::float AS body_fat_percentage,\n\ttimestamp AS time\nFROM\n\tmetrics\nWHERE\n\tname = 'body_fat_percentage';"
    }
   ]
  },
  {
   "title": "步行步幅",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(AVG((data ->> 'qty') :: float), 0) AS cm,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'walking_step_length'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "站立时间",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 14, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM((data ->> 'qty') :: float), 0) AS value,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'apple_stand_hour'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "HRV",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS HRV,\n  timestamp AS time\nFROM\n  metrics\nWHERE\n  name = 'heart_rate_variability'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()"
    }
   ]
  },
  {
   "title": "上楼速度",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(AVG((data ->> 'qty') :: float), 0) AS floor,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'stair_speed_up'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "步行速度",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 14, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(AVG((data ->> 'qty') :: float), 0) AS km,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'walking_speed'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "SPO",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS SPO,\n  timestamp AS time\nFROM\n  metrics\nWHERE\n  name = 'blood_oxygen_saturation'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()"
    }
   ]
  },
  {
   "title": "休息心率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\n  (data ->> 'qty') :: float AS QPM,\n  timestamp AS time\nFROM\n  metrics\nWHERE\n  name = 'resting_heart_rate'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()"
    }
   ]
  },
  {
   "title": "下楼速度",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 14, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(AVG((data ->> 'qty') :: float), 0) AS cm,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'stair_speed_down'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "环境音频暴露",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT\n\t(data ->> 'qty')::float AS db,\n\ttimestamp AS time\nFROM\n\tmetrics\nWHERE\n\tname = 'environmental_audio_exposure';"
    }
   ]
  },
  {
   "title": "呼吸频率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(AVG((data ->> 'qty') :: float), 0) AS QPM,\n  generate_series(\n    date_trunc('day', min(timestamp)),\n    date_trunc('day', max(timestamp)),\n    '1 day' :: interval\n  ) AS time\nFROM\n  metrics\nWHERE\n  name = 'respiratory_rate'\n  AND \"timestamp\" > $__timeFrom()\n  AND \"timestamp\" < $__timeTo()\nGROUP BY\n  date_trunc('day', timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "BMI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 15, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT\n\t(data ->> 'qty')::float AS BMI,\n\ttimestamp AS time\nFROM\n\tmetrics\nWHERE\n\tname = 'body_mass_index';"
    }
   ]
  }
 ]
}